# Site settings
title: Grayscale
email: your-email@domain.com
url: https://farqtech.github.io
description: "A portfolio website"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)


# Build settings
markdown: kramdown
permalink: pretty
